<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wjudger.proto

namespace WJudger;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WJudger.JudgeArgs</code>
 */
class JudgeArgs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>.WJudger.Language language = 3;</code>
     */
    protected $language = 0;
    /**
     * Generated from protobuf field <code>uint64 timelimit = 4;</code>
     */
    protected $timelimit = 0;
    /**
     * Generated from protobuf field <code>double memorylimit = 5;</code>
     */
    protected $memorylimit = 0.0;
    /**
     * Generated from protobuf field <code>string datapath = 6;</code>
     */
    protected $datapath = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type string $code
     *     @type int $language
     *     @type int|string $timelimit
     *     @type float $memorylimit
     *     @type string $datapath
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wjudger::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.WJudger.Language language = 3;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>.WJudger.Language language = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \WJudger\Language::class);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timelimit = 4;</code>
     * @return int|string
     */
    public function getTimelimit()
    {
        return $this->timelimit;
    }

    /**
     * Generated from protobuf field <code>uint64 timelimit = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimelimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->timelimit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double memorylimit = 5;</code>
     * @return float
     */
    public function getMemorylimit()
    {
        return $this->memorylimit;
    }

    /**
     * Generated from protobuf field <code>double memorylimit = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setMemorylimit($var)
    {
        GPBUtil::checkDouble($var);
        $this->memorylimit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string datapath = 6;</code>
     * @return string
     */
    public function getDatapath()
    {
        return $this->datapath;
    }

    /**
     * Generated from protobuf field <code>string datapath = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDatapath($var)
    {
        GPBUtil::checkString($var, True);
        $this->datapath = $var;

        return $this;
    }

}

