<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

namespace WJudger;

if (false) {
    /**
     * This class is deprecated. Use WJudger\JudgeArgs\Language instead.
     * @deprecated
     */
    class JudgeArgs_Language {}
}
class_exists(JudgeArgs\Language::class);
@trigger_error('WJudger\JudgeArgs_Language is deprecated and will be removed in the next major release. Use WJudger\JudgeArgs\Language instead', E_USER_DEPRECATED);

