<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wjudger.proto

namespace WJudger;

use UnexpectedValueException;

/**
 * Protobuf type <code>WJudger.JudgeStatus</code>
 */
class JudgeStatus
{
    /**
     * Generated from protobuf enum <code>OK = 0;</code>
     */
    const OK = 0;
    /**
     * Generated from protobuf enum <code>UNAUTHENTICATED = 1;</code>
     */
    const UNAUTHENTICATED = 1;
    /**
     * Generated from protobuf enum <code>BUSY = 2;</code>
     */
    const BUSY = 2;

    private static $valueToName = [
        self::OK => 'OK',
        self::UNAUTHENTICATED => 'UNAUTHENTICATED',
        self::BUSY => 'BUSY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

