<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

namespace WJudger;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WJudger.JudgeReply</code>
 */
class JudgeReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.WJudger.JudgeReply.ResultType resultType = 1;</code>
     */
    protected $resultType = 0;
    /**
     * Generated from protobuf field <code>.WJudger.CompileResult compileResult = 2;</code>
     */
    protected $compileResult = null;
    /**
     * Generated from protobuf field <code>.WJudger.ExecuteResult executeResult = 3;</code>
     */
    protected $executeResult = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $resultType
     *     @type \WJudger\CompileResult $compileResult
     *     @type \WJudger\ExecuteResult $executeResult
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wjudger::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.WJudger.JudgeReply.ResultType resultType = 1;</code>
     * @return int
     */
    public function getResultType()
    {
        return $this->resultType;
    }

    /**
     * Generated from protobuf field <code>.WJudger.JudgeReply.ResultType resultType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResultType($var)
    {
        GPBUtil::checkEnum($var, \WJudger\JudgeReply\ResultType::class);
        $this->resultType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.WJudger.CompileResult compileResult = 2;</code>
     * @return \WJudger\CompileResult|null
     */
    public function getCompileResult()
    {
        return $this->compileResult;
    }

    public function hasCompileResult()
    {
        return isset($this->compileResult);
    }

    public function clearCompileResult()
    {
        unset($this->compileResult);
    }

    /**
     * Generated from protobuf field <code>.WJudger.CompileResult compileResult = 2;</code>
     * @param \WJudger\CompileResult $var
     * @return $this
     */
    public function setCompileResult($var)
    {
        GPBUtil::checkMessage($var, \WJudger\CompileResult::class);
        $this->compileResult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.WJudger.ExecuteResult executeResult = 3;</code>
     * @return \WJudger\ExecuteResult|null
     */
    public function getExecuteResult()
    {
        return $this->executeResult;
    }

    public function hasExecuteResult()
    {
        return isset($this->executeResult);
    }

    public function clearExecuteResult()
    {
        unset($this->executeResult);
    }

    /**
     * Generated from protobuf field <code>.WJudger.ExecuteResult executeResult = 3;</code>
     * @param \WJudger\ExecuteResult $var
     * @return $this
     */
    public function setExecuteResult($var)
    {
        GPBUtil::checkMessage($var, \WJudger\ExecuteResult::class);
        $this->executeResult = $var;

        return $this;
    }

}

