<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

namespace WJudger;

if (false) {
    /**
     * This class is deprecated. Use WJudger\JudgeReply\ResultType instead.
     * @deprecated
     */
    class JudgeReply_ResultType {}
}
class_exists(JudgeReply\ResultType::class);
@trigger_error('WJudger\JudgeReply_ResultType is deprecated and will be removed in the next major release. Use WJudger\JudgeReply\ResultType instead', E_USER_DEPRECATED);

