<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

namespace WJudger;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WJudger.SimpleArgs</code>
 */
class SimpleArgs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 judgerid = 1;</code>
     */
    protected $judgerid = 0;
    /**
     * Generated from protobuf field <code>string token = 2;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>.WJudger.Language language = 4;</code>
     */
    protected $language = 0;
    /**
     * Generated from protobuf field <code>string input = 5;</code>
     */
    protected $input = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $judgerid
     *     @type string $token
     *     @type string $code
     *     @type int $language
     *     @type string $input
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wjudger::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 judgerid = 1;</code>
     * @return int
     */
    public function getJudgerid()
    {
        return $this->judgerid;
    }

    /**
     * Generated from protobuf field <code>uint32 judgerid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setJudgerid($var)
    {
        GPBUtil::checkUint32($var);
        $this->judgerid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 2;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.WJudger.Language language = 4;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>.WJudger.Language language = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \WJudger\Language::class);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string input = 5;</code>
     * @return string
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * Generated from protobuf field <code>string input = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;

        return $this;
    }

}

