<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

namespace WJudger;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WJudger.SimpleReply</code>
 */
class SimpleReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool compileError = 1;</code>
     */
    protected $compileError = false;
    /**
     * Generated from protobuf field <code>uint32 runtimeError = 2;</code>
     */
    protected $runtimeError = 0;
    /**
     * Generated from protobuf field <code>string compileErrorMessage = 3;</code>
     */
    protected $compileErrorMessage = '';
    /**
     * Generated from protobuf field <code>string runtimeErrorMessage = 4;</code>
     */
    protected $runtimeErrorMessage = '';
    /**
     * Generated from protobuf field <code>uint64 timeused = 5;</code>
     */
    protected $timeused = 0;
    /**
     * Generated from protobuf field <code>double memoryused = 6;</code>
     */
    protected $memoryused = 0.0;
    /**
     * Generated from protobuf field <code>string output = 7;</code>
     */
    protected $output = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $compileError
     *     @type int $runtimeError
     *     @type string $compileErrorMessage
     *     @type string $runtimeErrorMessage
     *     @type int|string $timeused
     *     @type float $memoryused
     *     @type string $output
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wjudger::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool compileError = 1;</code>
     * @return bool
     */
    public function getCompileError()
    {
        return $this->compileError;
    }

    /**
     * Generated from protobuf field <code>bool compileError = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCompileError($var)
    {
        GPBUtil::checkBool($var);
        $this->compileError = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 runtimeError = 2;</code>
     * @return int
     */
    public function getRuntimeError()
    {
        return $this->runtimeError;
    }

    /**
     * Generated from protobuf field <code>uint32 runtimeError = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRuntimeError($var)
    {
        GPBUtil::checkUint32($var);
        $this->runtimeError = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string compileErrorMessage = 3;</code>
     * @return string
     */
    public function getCompileErrorMessage()
    {
        return $this->compileErrorMessage;
    }

    /**
     * Generated from protobuf field <code>string compileErrorMessage = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompileErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->compileErrorMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string runtimeErrorMessage = 4;</code>
     * @return string
     */
    public function getRuntimeErrorMessage()
    {
        return $this->runtimeErrorMessage;
    }

    /**
     * Generated from protobuf field <code>string runtimeErrorMessage = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntimeErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->runtimeErrorMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timeused = 5;</code>
     * @return int|string
     */
    public function getTimeused()
    {
        return $this->timeused;
    }

    /**
     * Generated from protobuf field <code>uint64 timeused = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeused($var)
    {
        GPBUtil::checkUint64($var);
        $this->timeused = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double memoryused = 6;</code>
     * @return float
     */
    public function getMemoryused()
    {
        return $this->memoryused;
    }

    /**
     * Generated from protobuf field <code>double memoryused = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setMemoryused($var)
    {
        GPBUtil::checkDouble($var);
        $this->memoryused = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string output = 7;</code>
     * @return string
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * Generated from protobuf field <code>string output = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkString($var, True);
        $this->output = $var;

        return $this;
    }

}

