<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ExecuteResult</code>
 */
class ExecuteResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string testcase = 1;</code>
     */
    protected $testcase = '';
    /**
     * Generated from protobuf field <code>uint64 timeused = 2;</code>
     */
    protected $timeused = 0;
    /**
     * Generated from protobuf field <code>double memoryused = 3;</code>
     */
    protected $memoryused = 0.0;
    /**
     * Generated from protobuf field <code>uint32 score = 4;</code>
     */
    protected $score = 0;
    /**
     * Generated from protobuf field <code>string verdict = 5;</code>
     */
    protected $verdict = '';
    /**
     * Generated from protobuf field <code>string msg = 6;</code>
     */
    protected $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $testcase
     *     @type int|string $timeused
     *     @type float $memoryused
     *     @type int $score
     *     @type string $verdict
     *     @type string $msg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wjudger::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string testcase = 1;</code>
     * @return string
     */
    public function getTestcase()
    {
        return $this->testcase;
    }

    /**
     * Generated from protobuf field <code>string testcase = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTestcase($var)
    {
        GPBUtil::checkString($var, True);
        $this->testcase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timeused = 2;</code>
     * @return int|string
     */
    public function getTimeused()
    {
        return $this->timeused;
    }

    /**
     * Generated from protobuf field <code>uint64 timeused = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeused($var)
    {
        GPBUtil::checkUint64($var);
        $this->timeused = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double memoryused = 3;</code>
     * @return float
     */
    public function getMemoryused()
    {
        return $this->memoryused;
    }

    /**
     * Generated from protobuf field <code>double memoryused = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMemoryused($var)
    {
        GPBUtil::checkDouble($var);
        $this->memoryused = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 score = 4;</code>
     * @return int
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>uint32 score = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verdict = 5;</code>
     * @return string
     */
    public function getVerdict()
    {
        return $this->verdict;
    }

    /**
     * Generated from protobuf field <code>string verdict = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVerdict($var)
    {
        GPBUtil::checkString($var, True);
        $this->verdict = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 6;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

