<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>JudgeReply</code>
 */
class JudgeReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.JudgeReply.ResultType resultType = 1;</code>
     */
    protected $resultType = 0;
    /**
     * Generated from protobuf field <code>.CompileResult compileResult = 2;</code>
     */
    protected $compileResult = null;
    /**
     * Generated from protobuf field <code>.ExecuteResult executeResult = 3;</code>
     */
    protected $executeResult = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $resultType
     *     @type \CompileResult $compileResult
     *     @type \ExecuteResult $executeResult
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wjudger::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.JudgeReply.ResultType resultType = 1;</code>
     * @return int
     */
    public function getResultType()
    {
        return $this->resultType;
    }

    /**
     * Generated from protobuf field <code>.JudgeReply.ResultType resultType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResultType($var)
    {
        GPBUtil::checkEnum($var, \JudgeReply\ResultType::class);
        $this->resultType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CompileResult compileResult = 2;</code>
     * @return \CompileResult|null
     */
    public function getCompileResult()
    {
        return $this->compileResult;
    }

    public function hasCompileResult()
    {
        return isset($this->compileResult);
    }

    public function clearCompileResult()
    {
        unset($this->compileResult);
    }

    /**
     * Generated from protobuf field <code>.CompileResult compileResult = 2;</code>
     * @param \CompileResult $var
     * @return $this
     */
    public function setCompileResult($var)
    {
        GPBUtil::checkMessage($var, \CompileResult::class);
        $this->compileResult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ExecuteResult executeResult = 3;</code>
     * @return \ExecuteResult|null
     */
    public function getExecuteResult()
    {
        return $this->executeResult;
    }

    public function hasExecuteResult()
    {
        return isset($this->executeResult);
    }

    public function clearExecuteResult()
    {
        unset($this->executeResult);
    }

    /**
     * Generated from protobuf field <code>.ExecuteResult executeResult = 3;</code>
     * @param \ExecuteResult $var
     * @return $this
     */
    public function setExecuteResult($var)
    {
        GPBUtil::checkMessage($var, \ExecuteResult::class);
        $this->executeResult = $var;

        return $this;
    }

}

