<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wjudger.proto

if (false) {
    /**
     * This class is deprecated. Use JudgeArgs\Language instead.
     * @deprecated
     */
    class JudgeArgs_Language {}
}
class_exists(JudgeArgs\Language::class);
@trigger_error('JudgeArgs_Language is deprecated and will be removed in the next major release. Use JudgeArgs\Language instead', E_USER_DEPRECATED);

